const express = require("express");
const cors = require("cors");

const PORT = process.env.PORT || 3000;

const app = express();

app.use(cors());

app.get("/mammals", (req, res) => {
  res.send({
    invulnerable: [
      "Gelbhalsmaus",
      "Waldmaus",
      "Ostschermaus",
      "Reh",
      "Rothirsch",
      "Hausspitzmaus",
      "Siebenschläfer",
      "Alpenmurmeltier",
      "Steinmarder",
      "Dachs",
      "Erdmaus",
      "Feldmaus",
      "Westliche Hausmaus",
      "Östliche Hausmaus",
      "Rötelmaus",
      "Große Bartfledermaus",
      "Wasserfledermaus",
      "Großes Mausohr",
      "Kleine Bartfledermaus",
      "Fransenfledermaus",
      "Weißrandfledermaus",
      "Rauhautfledermaus",
      "Zwergfledermaus",
      "Mückenfledermaus",
      "Wanderratte",
      "Eichhörnchen",
      "Waldspitzmaus",
      "Schabrackenspitzmaus",
      "Zwergspitzmaus",
      "Wildschwein",
      "Maulwurf",
      "Fuchs",
    ],
    extinct: [
      "Wisent",
      "Auerochse",
      "Wildpferd",
      "Ostigel",
      "Bayerische Kleinwühlmaus",
      "Langflügelfledermaus",
      "Europäischer Nerz",
      "Europäisches Ziesel",
      "Großer Tümmler",
      "Braunbär",
    ],
    threatened: [
      "Zwergwal",
      "Feldhamster",
      "Luchs",
      "Nymphenfledermaus",
      "Graues Langohr",
      "Hausratte",
      "Große Hufeisennase",
    ],
    endangered: [
      "Sumpfmaus",
      "Mopsfledermaus",
      "Gartenschläfer",
      "Baltische Kegelrobbe",
      "Bechsteinfledermaus",
      "Wimperfledermaus",
      "Sumpfspitzmaus",
      "Schweinswal",
      "Kleine Hufeisennase",
      "Waldbirkenmaus",
    ],
    vulnerable: [
      "Wolf",
      "Gartenspitzmaus",
      "Nordfledermaus",
      "Breitflügelfledermaus",
      "Wildkatze",
      "Atlantische Kegelrobbe",
      "Feldhase",
      "Fischotter",
      "Iltis",
      "Braunes Langohr",
    ],
    rare: [
      "Elch",
      "Alpenwaldmaus",
      "Steinbock",
      "Schneemaus",
      "Baumschläfer",
      "Alpenfledermaus",
      "Weißschnauzendelfin",
      "Schneehase",
      "Helgoländer Hausmaus",
    ],
    pre: [
      "Eurpäischer Biber",
      "Feldspitzmaus",
      "Westigel",
      "Baummarder",
      "Zwergmaus",
      "Haselmaus",
      "Wasserspitzmaus",
      "Großer Abendsegler",
      "Wildkaninchen",
      "Gämse",
    ],
    insufficient: [
      "Brandmaus",
      "Finnwal",
      "Goldschakal",
      "Gewöhnlicher Delfin",
      "Sibirisches Streifenhörnchen",
      "Hauskatze",
      "Weißseitendelfin",
      "Buckelwal",
      "Kleinwühlmaus",
      "Hermelin",
      "Steppeniltis",
      "Mauswiesel",
      "Teichfledermaus",
      "Kleinabendsegler",
      "Seehund",
      "Alpenspitzmaus",
      "Streifen-Backenhörnchen",
      "Baumstreifenhörnchen",
      "Zweifarbfledermaus",
    ],
  });
});

app.listen(PORT, () => {
  console.log("App started.");
});
